if: type != "push"

dist: trusty
language: c

env:
  global:
    - secure: PjPO5nJoIiDvakrwwzeYDVdhSlSyy6IKYNDFW1Ys12qJ+t0Y7bGBd7PgbSaDSzTp0UY/FmXtMsQAMU+3O4N7Bc7EGNyFwFQZ+dZdRlAGkKdUO1bWNob4B6IadsofTcYVcdSt0lYp//U6pGpqqJQd8gW7t1p7jUDzOZDnSY+XkNQwE6mmlBV3O3ZXrW3/xY6vjf4EE4Zx8rZvCP+iW1Bb/BTscdfol308paXXiQUH4ZuHZwSEZtjsgDnO9/yBhpnU3Sh6tvmLvTBhATqizYi5jcVqIZyjcxmXN1zQCypE2DpgpYdcLuXHPPSuw8wmPLYccBeth+ZOpIuAqjU9QUewRqrkDAO4jTuZZ2Q6LkmnWl4kgK4gHwbYew5r31D+NhgWeeDXNURzEcNhvUvOCVroFvmiaADIsHNwbTuKHdotBkXVvIbU41Tw3+7YJBsL7h8S9ZGeQ4zfvT8EnuN0O/tgzJzEAT2JBIqXDgfyqeMBiTkVjp0Yw/tBvdaHsSiW6y44dIzbqPaCbbRKxk7LRGIBjhlHZ4IWsXG9txTU1rs2qoyMHrNTodvAHM8tPq5QwIaYG3etoPe/yo1hfMEOJ7fqlEKEawGy/xvV+Msg/fp4ADFVYsK/Sindz2hzWfAmGQ4ZkLrts9bbw11vbqpQGZq5LP1etwTECsoQ9EbejNdMLb0=
    - BUILD_NAME=MXE.Cross.Compiler
    - TRAVIS_TAG=cc.core
  matrix:
    - MXE_TARGETS=i686-w64-mingw32.shared
    - MXE_TARGETS=i686-w64-mingw32.static
    - MXE_TARGETS=x86_64-w64-mingw32.shared
    - MXE_TARGETS=x86_64-w64-mingw32.static

install:
  - git clone https://github.com/mxe/mxe
  - sudo apt-get -qq update
  - sudo apt-get install -y autopoint gperf intltool p7zip-full lzip

before_script:
  - chmod +x clean_release.sh
  - if [ $MXE_TARGETS == "i686-w64-mingw32.shared" ]; then ./clean_release.sh; fi

script:
  - travis_wait 120 sleep infinity &
  - pushd mxe
  - make MXE_TARGETS=$MXE_TARGETS cc -j 4
  - popd

before_deploy:
  - mkdir artifacts
  - pushd mxe
  - md5sum pkg/* > pkg.md5
  - tar cJvf ../artifacts/$MXE_TARGETS.tar.xz usr pkg.md5 > /dev/null
  - popd

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  name: "$BUILD_NAME"
  tag_name: "$TRAVIS_TAG"
  target_commitish: "$TRAVIS_BRANCH"
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: "$TRAVIS_BRANCH"

after_deploy:
  - chmod +x refresh.sh
  - ./refresh.sh

